---
title: "growth_markets"
author: "Aisah Taufik Hidayat Abdullah"
date: "2022-07-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
library(mapview)
library(nycgeo)
library(ggspatial)
library(tmap)
library(mapboxapi)
library(dotenv)

library(ggplot2) # plot statis
library(plotly) # plot interaktif
library(glue) # setting tooltip
library(scales) # mengatur skala pada plot

```

```{r load-data}
grow_nyc <- readRDS("./data/green_markets")

# preview
glimpse(grow_nyc)
```

```{r}
grow_nyc_sf <- st_as_sf(x = grow_nyc,
         coords = c("longitude","latitude"),
         crs = 4326) %>% 
         st_transform(crs = 2263)

# check crs
st_crs(grow_nyc_sf)

# preview
head(grow_nyc_sf, 20)
```

```{r}
unique(grow_nyc_sf$type)
```

```{r get-community-districts-geo}
nyc_cd <- nyc_boundaries(
  geography = 'cd',
) %>% 
  st_transform(2263)


#preview df
glimpse(nyc_cd)
```

```{r spatial-join}
nyc_cd_grow <- nyc_cd %>% 
  st_join(grow_nyc_sf)

head(nyc_cd_grow, 50)
```
## Page 1 - Overview
### 1.a

```{r}
# Total of all NYC Growth Market
count(grow_nyc)
```

```{r}
# Total of Borough in NYC
length(unique(nyc_cd_grow$county_name))
```


```{r}
# Total of All market by type
nyc_cd_grow_type <- 
  nyc_cd_grow %>%
  filter(type != "NA")

length(unique(nyc_cd_grow_type$type))
```

### 1.b

```{r}
# bar plot
nyc_grow_count <- 
  nyc_cd_grow_type %>%
  group_by(borough_name, county_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) 
nyc_grow_count

# penambahan tooltip
nyc_grow_count <- 
  nyc_grow_count %>%
  mutate(label = glue("County: {county_name}
                      Growth Market: {count} Stores"))

# ggplot
plot1 <- nyc_grow_count %>%
  ggplot(aes(x=count,
             y=reorder(borough_name, count),
             fill=count,
             text=label)) +
  geom_col() +
  scale_fill_gradient(low = "#FFF80A", high = "#605CA8") +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = NULL,
       x = 'Growth Market Count',
       y = NULL)

ggplotly(plot1, tooltip = "text")

```


### Page 2 - Store

```{r}
# Sum of each market by type with input from user based on borough

nyc_grow_store <- 
  nyc_cd_grow_type %>%
  filter(borough_name == 'Manhattan') %>% #input$input_borough
  group_by(type, county_name) %>%
  summarise(count = n())

unique(nyc_cd_grow_type$borough_name)

nyc_grow_store

# penambahan tooltip
nyc_grow_store <- 
  nyc_grow_store %>%
  mutate(label = glue("County: {county_name}
                     Growth Market: {count} Stores"))


# ggplot
plot2 <- nyc_grow_store %>%
  ggplot(aes(x = type,
             y = count,
             fill = count,
             text = label)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = NULL,
       x = NULL,
       y = 'Stores')

# plotly
ggplotly(plot2, tooltip = 'text')

```


## Page 3 - Map
### 3.a

```{r interactive-popup-map}
tmap_mode("view")


# import ntas with census data
nyc_ntas <- nyc_boundaries(geography = "nta",
               add_acs_data = T) %>% 
  st_transform(2263)


nyc_ntas_grow_plot_tm <- tm_shape(nyc_ntas) +
  tm_fill(col = "pop_ba_above_pct_est",
          palette = "cividis",
          alpha = 0.7,
          title = "% Bachelor's or Higher",
          popup.vars = c("Neighborhood" = "nta_name",
                         "County" = "borough_name"),
          legend.format = percent_format()) +
  tm_layout(title = "Bachelor's or Higher and GROW NYC Markets") +
  tm_shape(grow_nyc_sf) +
  tm_dots(
    col = "type",
    border.col = "white",
    border.lwd = 0.8,
    border.alpha = 0.5,
    palette = "Greens",
    title = "Market Type",
    popup.vars = c("Days" = "day",
                   "Time" = "compost_hours",
                   "Duration" = "duration")) +
  tm_scale_bar()

tmap_save(nyc_ntas_grow_plot_tm,
          filename = "./images/tmap_nyc_ntas_grow.png")
tmap_save(nyc_ntas_grow_plot_tm,
          filename = "./images/tmap_nyc_ntas_grow.html")

nyc_ntas_grow_plot_tm
```


## Page 4 - Data
### 4.a

```{r}
head(grow_nyc)
```

